#!/bin/bash
# Program to output a system information page

TITLE="System Information Report $HOSTNAME" #constant HOSTNAME 系统变量
CURRENT_TIME=$(date +"%x %r %Z") #what's this?
TIME_STAMP="GENERATED, $CURRENT_TIME, by $USER" #USER 系统变量

#Here document 一种新的IO重定向方式, 可以将文本重定向到命令的标准输入中

cat << _EOF_
<html>
	<head>
		<title> $TITLE </title>
	</head>
	<body>
		<h1> $TITLE </h1>
		<p> $TIME_STAMP </p>
	</body>
</html>
_EOF_
